In [1]:
# ==========================================
# IMPORT LIBRARIES
# ==========================================

import pandas as pd
from sklearn.preprocessing import LabelEncoder

print("="*60)
print("LIBRARIES IMPORTED SUCCESSFULLY")
print("="*60)

============================================================
LIBRARIES IMPORTED SUCCESSFULLY
============================================================

In [2]:
# ==========================================
# INSTALL BINARY ENCODER
# ==========================================

!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 1.7 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

In [3]:
# ==========================================
# IMPORT BINARY ENCODER
# ==========================================

import category_encoders as ce

print("Binary Encoder Imported Successfully")

Binary Encoder Imported Successfully

In [4]:
# ==========================================
# CREATE EMPLOYEE DATASET
# ==========================================

data = {
    "Employee_ID":[501,502,503,504,505,506,507,508],
    "Employee_Name":["Rohan","Priya","Amit","Neha","Kiran","Meera","Vikas","Pooja"],
    "Department":["HR","IT","Finance","IT","Marketing","HR","Finance","Marketing"],
    "Gender":["Male","Female","Male","Female","Male","Female","Male","Female"],
    "City":["Ahmedabad","Surat","Rajkot","Vadodara","Ahmedabad","Surat","Rajkot","Vadodara"]
}

df = pd.DataFrame(data)

print("Original Employee Dataset")

display(df)

Original Employee Dataset

   Employee_ID Employee_Name Department  Gender       City
0          501         Rohan         HR    Male  Ahmedabad
1          502         Priya         IT  Female      Surat
2          503          Amit    Finance    Male     Rajkot
3          504          Neha         IT  Female   Vadodara
4          505         Kiran  Marketing    Male  Ahmedabad
5          506         Meera         HR  Female      Surat
6          507         Vikas    Finance    Male     Rajkot
7          508         Pooja  Marketing  Female   Vadodara

In [5]:
# ==========================================
# LABEL ENCODING
# ==========================================

le = LabelEncoder()

label_df = df.copy()

label_df["Department"] = le.fit_transform(label_df["Department"])

print("Label Encoded Dataset")

display(label_df)

Label Encoded Dataset

   Employee_ID Employee_Name  Department  Gender       City
0          501         Rohan           1    Male  Ahmedabad
1          502         Priya           2  Female      Surat
2          503          Amit           0    Male     Rajkot
3          504          Neha           2  Female   Vadodara
4          505         Kiran           3    Male  Ahmedabad
5          506         Meera           1  Female      Surat
6          507         Vikas           0    Male     Rajkot
7          508         Pooja           3  Female   Vadodara

In [6]:
# ==========================================
# LABEL ENCODER CLASSES
# ==========================================

print("Department Classes")

print(le.classes_)

Department Classes
['Finance' 'HR' 'IT' 'Marketing']

In [7]:
# ==========================================
# ONE HOT ENCODING
# ==========================================

one_hot = pd.get_dummies(
    df,
    columns=["Gender"],
    dtype=int
)

print("One Hot Encoded Dataset")

display(one_hot)

One Hot Encoded Dataset

   Employee_ID Employee_Name Department       City  Gender_Female  Gender_Male
0          501         Rohan         HR  Ahmedabad              0            1
1          502         Priya         IT      Surat              1            0
2          503          Amit    Finance     Rajkot              0            1
3          504          Neha         IT   Vadodara              1            0
4          505         Kiran  Marketing  Ahmedabad              0            1
5          506         Meera         HR      Surat              1            0
6          507         Vikas    Finance     Rajkot              0            1
7          508         Pooja  Marketing   Vadodara              1            0

In [8]:
# ==========================================
# BINARY ENCODING
# ==========================================

binary = ce.BinaryEncoder(cols=["City"])

binary_df = binary.fit_transform(df)

print("Binary Encoded Dataset")

display(binary_df)

Binary Encoded Dataset

   Employee_ID Employee_Name Department  Gender  City_0  City_1  City_2
0          501         Rohan         HR    Male       0       0       1
1          502         Priya         IT  Female       0       1       0
2          503          Amit    Finance    Male       0       1       1
3          504          Neha         IT  Female       1       0       0
4          505         Kiran  Marketing    Male       0       0       1
5          506         Meera         HR  Female       0       1       0
6          507         Vikas    Finance    Male       0       1       1
7          508         Pooja  Marketing  Female       1       0       0

In [9]:
# ==========================================
# SHAPE COMPARISON
# ==========================================

print("Original Shape :", df.shape)

print("Label Encoding Shape :", label_df.shape)

print("One-Hot Encoding Shape :", one_hot.shape)

print("Binary Encoding Shape :", binary_df.shape)

Original Shape : (8, 5)
Label Encoding Shape : (8, 5)
One-Hot Encoding Shape : (8, 6)
Binary Encoding Shape : (8, 7)

In [10]:
# ==========================================
# CONCLUSION
# ==========================================

print("="*60)
print("DATA ENCODING COMPLETED SUCCESSFULLY")
print("="*60)

print("""
1. Label Encoding converted Department into numeric values.
2. One-Hot Encoding converted Gender into separate binary columns.
3. Binary Encoding converted City into binary representation.
4. Different encoding techniques are used based on the machine learning algorithm and dataset.
""")

============================================================
DATA ENCODING COMPLETED SUCCESSFULLY
============================================================

1. Label Encoding converted Department into numeric values.
2. One-Hot Encoding converted Gender into separate binary columns.
3. Binary Encoding converted City into binary representation.
4. Different encoding techniques are used based on the machine learning algorithm and dataset.